title: SECCOM 2018
safe: true
timezone: America/Sao_Paulo

default:
    - scope:
        path: "assets/img"
    - values:
        image: true;

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

url: "seccom-ufsc.github.io"
baseurl: "/2018"  # project name
permalink: /:year-:month-:day/:title:output_ext

# Pagination Settings
paginate: 5
paginate_path: "/news/page:num"
